name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and start local server
        run: |
          npm run build
          npm install -g serve
          serve -s build -l 3000 &

      - name: Run unit tests
        run: npm run test

      - name: Wait for server to start
        run: sleep 5

      - name: Run end-to-end tests
        run: npm run cy:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Check test coverage
        run: |
          npm install -g istanbul
          istanbul check-coverage --statement 80 --branch 80 --function 80 --lines 80 ./coverage/coverage-final.json
