name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and start local server
        run: |
          npm run build
          npm install -g serve
          serve -s build -l 3000 &

      - name: Run unit tests
        run: npm run test

      - name: Run tests and generate coverage report
        run: npm test -- --coverage
  
      - name: Check test coverage
        run: |
          # Extract the coverage percentage from the generated coverage report.
          COVERAGE_PERCENTAGE=$(cat coverage/lcov-report/index.html | grep -oP 'Statements</th><td class=".*"><span>([^<]+)%' | grep -oP '(\d+(\.\d+)?)')

          # Compare the coverage percentage with the desired threshold (80%).
          if (( $(echo "$COVERAGE_PERCENTAGE >= 80" | bc -l) )); then
            echo "Code coverage is above 80%."
          else
            echo "Code coverage is below 80%."
            exit 1  # You can choose to fail the workflow if coverage is below the threshold.
          fi
